title: "Chispi-Page || Dashboard Personal"
description: "Portfolio, Devlogs, Proyectos y Recursos"
baseurl: "/Chispi-Page"
url: "https://ChispiDEV.github.io"

markdown: kramdown

# Plugins necesarios
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

plugins_dir: _plugins

# Configuración de paginación
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ":title - Página :num"

pagination_tag:
  enabled: true
  per_page: 5
  title: "Etiqueta: :tag - Página :num"
  permalink: /tags/:tag/page/:num/
  layout: tag

# Colecciones personalizadas
collections:
  projects:
    output: true

# Configuración por defecto para posts y colecciones
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es
      show_header: true
      hero: false   # o true, si la mayoría lo usan
  - scope:
      path: ""
      type: "posts"
    values:
      layout: devlog
      lang: es
  - scope:
      path: "projects"
      type: "projects"
    values:
      layout: project
      lang: es
  - scope:
      path: ""
      type: "tags"
    values:
      layout: tag
  - scope:
      path: ""
    values:
      layout: default
      lang: es

# Soporte para múltiples idiomas (manual)
languages: ["es", "en"]
default_lang: "es"

# Configuración de assets
assets:
  css:
    main: "/assets/css/style.css"
    vendors:
      - "/assets/css/vendors/tippy.css"
      - "/assets/css/vendors/particles.css"
  
  js:
    main: "/assets/js/app.js"
    vendors:
      - "/assets/js/vendors/particles.js"
      - "/assets/js/vendors/tippy.js"
    modules:
      - "/assets/js/modules/sidebar.js"
      - "/assets/js/modules/scroll.js"
      - "/assets/js/modules/theme.js"
      - "/assets/js/modules/language.js"
      - "/assets/js/modules/particles.js"
      - "/assets/js/modules/tooltips.js"
      - "/assets/js/modules/popups.js"
    config:
      - "/assets/particles/particles-config.js"

# Orden de carga (importante para dependencias)
load_order:
  css:
    - vendors
    - main
  js:
    - vendors
    - config
    - modules
    - main

# CDNs externos
cdns:
  css:
    - "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
  js:
    - "https://kit.fontawesome.com/98ca02228e.js"
    - "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    - "https://www.googletagmanager.com/gtag/js?id=G-KKN4WJL07V"

# Archivos/carpetas que no deben procesarse
exclude:
  - node_modules
  - build.js
  - esbuild.config.js
  - package.json
  - package-lock.json
