# Configuración principal de Jekyll
title: "Chispi-Page || Dashboard Personal"
description: "Portfolio, Devlogs, Proyectos y Recursos"
baseurl: "/Chispi-Page"
url: "https://ChispiDEV.github.io"

# Configuración de build
markdown: kramdown
permalink: pretty
timezone: Europe/Madrid

# Plugins necesarios
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier

plugins_dir: _plugins

# Minificación (con jekyll-minifier)
minifier:
  compress_css: true
  compress_javascript: true
  remove_comments: true
  remove_intertag_spaces: false

# Configuración de paginación
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ":title - Página :num"

pagination_tag:
  enabled: true
  per_page: 5
  title: "Etiqueta: :tag - Página :num"
  permalink: /tags/:tag/page/:num/
  layout: tag

# Colecciones personalizadas
collections:
  posts:
    output: true
    permalink: /blog/:title/
  projects:
    output: true
    permalink: /proyectos/:title/

# Configuración por defecto para posts y colecciones
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es
      show_header: true
      hero: false   # o true, si la mayoría lo usan
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      lang: "es"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: "en"
    values:
      lang: "en"

# Soporte para múltiples idiomas (manual)
languages: ["es", "en"]
default_lang: "es"

# Excluir archivos de desarrollo
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - build-scripts.js
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache
  - .jekyll-cache

# Assets configuration
assets:
  css:
    main: "/assets/css/style.css"
  js:
    main: "/assets/js/app.js"

# CDNs
cdns:
  css:
    - "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
  js:
    - "https://kit.fontawesome.com/98ca02228e.js"
    - "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"

# Datos del sitio
data:
  buttons:
    es:
      - text: "Sobre mí"
        url: "/sobre-mi.html"
        class: "btn--primary"
      - text: "Proyectos"
        url: "/proyectos.html"
        class: "btn--secondary"
      - text: "Contacto"
        url: "/contacto.html"
        class: "btn--outline"
    en:
      - text: "About Me"
        url: "/sobre-mi.html"
        class: "btn--primary"
      - text: "Projects"
        url: "/proyectos.html"
        class: "btn--secondary"
      - text: "Contact"
        url: "/contacto.html"
        class: "btn--outline"