# Configuración específica para producción
url: "https://chispidev.github.io/Chispi-Page"  

# Assets optimizados para producción
assets:
  css:
    main: "/assets/css/style.css"
    vendors: []  # Ya incluidos en el bundle
  
  js:
    main: "/assets/js/dist/app.bundle.js"
    vendors: []  # Ya incluidos en el bundle
    modules: []  # Ya incluidos en el bundle

# CDNs optimizados
cdns:
  css:
    - "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
  js:
    - "https://kit.fontawesome.com/98ca02228e.js"
    - "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"

# Optimizaciones de Jekyll
permalink: pretty
timezone: Europe/Madrid

# Comprimir HTML
compress_html:
  clippings: all
  comments: all
  blanklines: false

# Excluir archivos de desarrollo
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - build-scripts.js
  - README.md
  - Gemfile
  - Gemfile.lock

# Incluir solo lo necesario
include:
  - _pages
  - _posts
  - _projects
  - assets/css/style.css
  - assets/js/dist/app.bundle.js